import type { jsPDF } from 'jspdf';

declare module 'jspdf' {
  interface jsPDFAPI {
    setFontAlegreyaMedium(): jsPDF;
    setFontCustom(fontName: string, fontData: string, fontStyle?: number, fontFlags?: number): jsPDF;
  }
}

export function setFontAlegreyaMedium(jsPDFAPI: typeof jsPDF.API) {
  jsPDFAPI.setFontAlegreyaMedium = function () {
    const fontData = atob('AAAAAAAAAAD/sP+w8AAAAHgAeABgAHgAYAAAAAWADfAf8D+AJ/A/4D2ABYAAAABwD3Afvn/+f/Af8BzgAAA8AH4MZjhm8H3AF4Af8Dvw87DD8AHgAAAAQDnwf/B/MGewZ/Bt8A7gD/AMOAwQAAB4AHgAQAAAAAPAH/h//GAOQAQAAGAGeBw/+A/wAAAgAHwAPAD4AHwANAAAAAGAAYABgB/wH/ADgAOAA4AAAAAEAD4APAA4AAAAAAGAAYABgAOAAAAAAAAwADAAMAAAAAwA/A/w/wDwAAAAA8AP8A5wHDAcMBwwD/AHwAAACBAYEB/wH/AQEAAQAAAEEAwwHPAd8B+wDzAAcABgAAAMDA2MGYwf2B/4DvAAAABgAeAD4A9gH/wf/ABgAAAADB+MH4wd2B34HPAAAAHAB/AP8B8wOzAz8CHgAAAeAB4MHDwc+B/AHwAcAAAAAEAe8D/wJxg3kD/wHeAAAAcAD4wf3Bj4HPAP4AfAAAAAAAcwBzAGMAAAAAQHPgc8BjgAAAOAA4AHgAbABsAMYAxgAAAGwAbABsAGwAbABsAGwAbAAAAIIAxgDGAGwAbAA4ADgAMAAAAAAMewx7DsMHwAOAAAAAPgD/gePDn+N/ZuNmzjb/Jv8H8wODAf4A/AAAAAMAHwD/A/kHmAf5A/8AfwAHAAEAAAABBgMH/wf/BjMGcwfzB/8DngAAAHgB/gP/BwcGAwYDhgMHhwePAAgAAAABBgMH/wf/BgMGAQYDBwMH/gP+APgAAAABBgMH/wf/BmMGYwZjB6cHBwAAAAEGAwf/B/8GMwYxBzAHgAAAAHgB/gP/BwcGAwYThjMHPwe/BzAAAAABBgMH/wf/BjEAIAAgBmEH/wf/BgEEAQAABAEGAwf/B/8GAQABAAAEAGf/x//H/wQAAAAAAQYDB/8H/wZxAPwH3gePBwOGAQAAAAAGAwf/B/8GAwADAAMADwAAAAEEDwf/B8EH+AH/AB+APwP4B8EH/wf/BAEAAAQBBgMH/wf/A+EB8AB8BD4H/4f/hgAEAAAAAHgB/gP/BwcGAwYDBgMHBwf+A/wA8AAAAAEGAwf/B/8GMQYxB/AH4APAAAAAeAH+A/8HBwYDBgOGA8cHx/7j/HDwcAAAAQYDB/8H/wYxBjwH/gfvA8OAAQAAAAMDzwfnBvGGcwY/B78HHgAAB4AHAAYBB/8H/wf/BgEHgAeAAAAEAAf8B/8H/wQDAAMEAwf/B/4H+AQAAAAGAAeAB/gH/wQfBB8E/gfwB4AGAAAABgAHwAf4B/8EHwYfB/wH4Af+BH+ADwR/B/gHwAYAAAAGAwYDBw8H3wf4BPkF/wefBwcGAwQBAAAGAAcAB+EH/wR/BP8HwQeABgAAAAGDB4cGHwY/BvkH4wfDBw8GDwAAAAAH/8f/xgBEAEAADgAP4AH+AB/AAcAABABGAEf/x//AAAACAB4AfAHwAfAAfAAeAAIAAAAAYABgAGAAYABgAGAAYAAAAAYABwADAAEAAAAABgDvAM8A2wD/AP8AAwACAAAEAAf/j/+AYYBhgHuAfwA+AAAAPAB/AP8AwwDDAOMAwgAAAA8AP4B/gGGEYYf/j/+PAYABgAAAPAB/AP8A0wDzAPMAcwAAAGCB/4P/h/+MYIAAAAIAf/D/8M2wzbD9sPnhgMAABACH/4//hGCAYIB/gH+AP4AAgAAAwQz/Dv8E8wAAAGAWf/Z/8EAAAAQAh/+P/4QOgH8Ad4BhwGCAAAQAh/+P/4QAgAAAwQD/AP8A8wDAAOMA/wB/AMEAwQD/AP8AIQAAAMEA/wD/APMAwADjAP8AfwABAAAAHAB/AP8AwwDDAP8A/gA8AAAAwBD/8P/w47DDEOMA/wB+AAAAHgB/AP8AwwDDMP/w//DAMAAAwQD/AP8A/wDhAOAAAAAnAPcA+4DdAP8A7gAAAMAB/wP/AMMAwwAAAMAA/wD/AIMAwwD/AP8A4wADAAAAwAD8AP8AjwDfAPwA4AAAAMAA+AD/AI8A3wD4AP8An4CPAPwA8ADAAAAAwwDnAP8A/AC/AP8AwwCBAAAAwDD4cP/gj8CfAPwA4AAAAOEA5wDPAP0A+wDnAMcAAAAQA7uH/8buxABAAAAAAAAP////8AAEAEbux//Du4AQAAAACAA4ADAAOAA4ABgAOAAwAAAA==');
    const fontStyle = atob('AwUGCQgMDAQGBQcJBQYFBgkHCQcIBwgICAgFBQgJCQcOCwoLDAoJCw0HBgsJDg0MCgwLCQoMCxAMCgoGBgUJCAYJCQgKCAYJCgUFCQUOCgkJCQcHBgoIDQkICAYFBgk=');
    return this.setFontCustom(
      fontData,
      fontStyle,
      32,
      16 | 65536
    );
  };
}
